runtime: nodejs20  # Asegúrate de usar la versión correcta de Node.js
env: standard

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5